apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jarvis-core-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jarvis-core-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jarvis-core-cluster-role
subjects:
- kind: ServiceAccount
  name: jarvis-core-service-account
  namespace: jarvis-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-core-service-account
  namespace: jarvis-v2
  annotations:
    iam.gke.io/gcp-service-account: jarvis-core-sa@your-project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-admin-role
  namespace: jarvis-v2
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-admin-role-binding
  namespace: jarvis-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jarvis-admin-role
subjects:
- kind: User
  name: jarvis-admin@your-domain.com
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: jarvis-admin-service-account
  namespace: jarvis-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-admin-service-account
  namespace: jarvis-v2
  annotations:
    iam.gke.io/gcp-service-account: jarvis-admin-sa@your-project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-user-role
  namespace: jarvis-v2
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
  resourceNames: ["jarvis-core-*", "jarvis-web-*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-user-role-binding
  namespace: jarvis-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jarvis-user-role
subjects:
- kind: User
  name: jarvis-user@your-domain.com
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: jarvis-user-service-account
  namespace: jarvis-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-user-service-account
  namespace: jarvis-v2
  annotations:
    iam.gke.io/gcp-service-account: jarvis-user-sa@your-project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-readonly-role
  namespace: jarvis-v2
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-readonly-role-binding
  namespace: jarvis-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jarvis-readonly-role
subjects:
- kind: User
  name: jarvis-readonly@your-domain.com
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: jarvis-readonly-service-account
  namespace: jarvis-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-readonly-service-account
  namespace: jarvis-v2
  annotations:
    iam.gke.io/gcp-service-account: jarvis-readonly-sa@your-project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-monitoring-role
  namespace: jarvis-v2-monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "podmonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-monitoring-role-binding
  namespace: jarvis-v2-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jarvis-monitoring-role
subjects:
- kind: ServiceAccount
  name: jarvis-monitoring-service-account
  namespace: jarvis-v2-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-monitoring-service-account
  namespace: jarvis-v2-monitoring
  annotations:
    iam.gke.io/gcp-service-account: jarvis-monitoring-sa@your-project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jarvis-prometheus-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jarvis-prometheus-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jarvis-prometheus-cluster-role
subjects:
- kind: ServiceAccount
  name: jarvis-prometheus-service-account
  namespace: jarvis-v2-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-prometheus-service-account
  namespace: jarvis-v2-monitoring
  annotations:
    iam.gke.io/gcp-service-account: jarvis-prometheus-sa@your-project-id.iam.gserviceaccount.com