apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-core
  namespace: jarvis-v2
  labels:
    app: jarvis-core
    version: "2.0"
    component: core
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jarvis-core
  template:
    metadata:
      labels:
        app: jarvis-core
        version: "2.0"
        component: core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/api/v2/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jarvis-core
              topologyKey: kubernetes.io/hostname
      containers:
      - name: jarvis-core
        image: jarvis/core:2.0.0
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: LOG_LEVEL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: REDIS_URL
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: MONGODB_URL
        - name: WORKER_COUNT
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: WORKER_COUNT
        - name: MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: MAX_CONNECTIONS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: jwt-secret
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: openweather-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v2/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v2/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: plugin-storage
          mountPath: /app/plugins
        - name: config-storage
          mountPath: /app/config
      volumes:
      - name: plugin-storage
        persistentVolumeClaim:
          claimName: jarvis-plugin-storage
      - name: config-storage
        configMap:
          name: jarvis-config
      nodeSelector:
        node-type: compute
      tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "compute"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-core
  namespace: jarvis-v2
  labels:
    app: jarvis-core
    version: "2.0"
    component: core
spec:
  type: ClusterIP
  selector:
    app: jarvis-core
  ports:
  - port: 8000
    targetPort: 8000
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvis-core-hpa
  namespace: jarvis-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvis-core
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60