apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-mobile
  namespace: jarvis-v2
  labels:
    app: jarvis-mobile
    version: "2.0"
    component: mobile
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jarvis-mobile
  template:
    metadata:
      labels:
        app: jarvis-mobile
        version: "2.0"
        component: mobile
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/api/v2/mobile/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jarvis-mobile
              topologyKey: kubernetes.io/hostname
      containers:
      - name: jarvis-mobile
        image: jarvis/mobile:2.0.0
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: LOG_LEVEL
        - name: CORE_SERVICE_URL
          value: "http://jarvis-core:8000"
        - name: AUDIO_SERVICE_URL
          value: "http://jarvis-audio:8001"
        - name: WORKER_COUNT
          value: "2"
        - name: ENABLE_MOBILE_API
          valueFrom:
            configMapKeyRef:
              name: jarvis-config
              key: ENABLE_MOBILE_API
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: jwt-secret
        - name: FCM_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: fcm-server-key
        - name: APNS_KEY
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: apns-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /api/v2/mobile/health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v2/mobile/health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      nodeSelector:
        node-type: compute
      tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "compute"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-mobile
  namespace: jarvis-v2
  labels:
    app: jarvis-mobile
    version: "2.0"
    component: mobile
spec:
  type: ClusterIP
  selector:
    app: jarvis-mobile
  ports:
  - port: 8002
    targetPort: 8002
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvis-mobile-hpa
  namespace: jarvis-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvis-mobile
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60