apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-web
  namespace: jarvis-v2
  labels:
    app: jarvis-web
    version: "2.0"
    component: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jarvis-web
  template:
    metadata:
      labels:
        app: jarvis-web
        version: "2.0"
        component: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jarvis-web
              topologyKey: kubernetes.io/hostname
      containers:
      - name: jarvis-web
        image: jarvis/web:2.0.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://jarvis-core:8000"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://jarvis-core:8000"
        - name: NEXT_PUBLIC_AUDIO_URL
          value: "http://jarvis-audio:8001"
        - name: NEXT_PUBLIC_AUDIO_WS_URL
          value: "ws://jarvis-audio:8001"
        - name: NEXT_PUBLIC_MOBILE_URL
          value: "http://jarvis-mobile:8002"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      nodeSelector:
        node-type: compute
      tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "compute"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-web
  namespace: jarvis-v2
  labels:
    app: jarvis-web
    version: "2.0"
    component: web
spec:
  type: ClusterIP
  selector:
    app: jarvis-web
  ports:
  - port: 3000
    targetPort: 3000
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvis-web-hpa
  namespace: jarvis-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvis-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60